[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.1"
blake3 = "1.3.3"
ff = "0.13.0"
num = "0.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
